# Generated by Django 2.2.3 on 2021-12-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EbazarApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
